In [2]:
import pandas as pd

In [3]:
incidents = pd.read_csv('NYPD_Use_of_Force_Incidents_20260415.csv')
members = pd.read_csv('NYPD_Use_of_Force__Members_of_Service_20260415.csv')
subjects = pd.read_csv('NYPD_Use_of_Force__Subjects_20260415.csv')

In [4]:
display(incidents.head())
display(members.head())
display(subjects.head())

,TRI Incident Number,ForceType,Occurrence Date,Incident Pct,Patrol Borough,YearMonthShort,BasisForEncounter
0,2024032962162,Physical Force,08/31/2024,13,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS
1,2024033962356,Physical Force,08/31/2024,14,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS
2,2024090962120,Physical Force,08/31/2024,71,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS
3,2024096962122,Physical Force,08/31/2024,77,PBBN,2024 Aug,CRIME/VIOLATION IN PROGRESS
4,2024081962083,Physical Force,08/31/2024,62,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS

,TRI Incident Number,ForceType,InjuryLevel,Member Injured,Rank Grouped,Assignment,Member Gender,Race
0,2022062962121,Physical Force,No Injury,N,Police Officer,SECTOR/RESPONSE AUTO,MALE,HISPANIC
1,2023020962075,Physical Force,No Injury,N,Police Officer,SECTOR/RESPONSE AUTO,MALE,HISPANIC
2,2023020962083,Physical Force,No Injury,N,Police Officer,SECTOR/RESPONSE AUTO,MALE,HISPANIC
3,2023020962134,Physical Force,No Injury,N,Police Officer,SECTOR/RESPONSE AUTO,MALE,HISPANIC
4,2023020962135,Physical Force,No Injury,N,Police Officer,SECTOR/RESPONSE AUTO,MALE,HISPANIC

,TRI Incident Number,Subject Injury Level,Subject Injured,Age,Subject Race,Subject Gender,Force Against MOS,Subject Used Force
0,2020020962067,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
1,2020020962143,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
2,2020024962080,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
3,2020025962038,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
4,2020025962049,No Injury,N,NaN,BLACK,MALE,Physical Force,Y

In [35]:
# Get all incidents that have only one subject, create a row with subject info and number of officers involved
counts = subjects['TRI Incident Number'].value_counts()
single_subject_tri = counts[counts < 2]
single_subject = subjects.copy()
single_tris = single_subject_tri.index.to_list()
single_subject = single_subject[single_subject['TRI Incident Number'].isin(single_tris)]
members_single_subject = members[members['TRI Incident Number'].isin(single_tris)]
print(len(single_subject))
print(len(members_single_subject))
single_subject.sort_values(by='TRI Incident Number', inplace=True)
single_tris.sort()
member_counts = []

for tri in single_tris:
  member_count = len(members_single_subject[members_single_subject['TRI Incident Number'] == tri])
  member_counts.append(member_count)

single_subject['MemberCount'] = member_counts
single_subject_full = pd.merge(left=incidents, right=single_subject, on='TRI Incident Number', suffixes=['_x', None])
print(single_subject_full.head())

51954
122495
   TRI Incident Number       ForceType Occurrence Date  Incident Pct  \
0        2024032962162  Physical Force      08/31/2024            13
1        2024033962356  Physical Force      08/31/2024            14
2        2024090962120  Physical Force      08/31/2024            71
3        2024096962122  Physical Force      08/31/2024            77
4        2024081962083  Physical Force      08/31/2024            62

  Patrol Borough YearMonthShort            BasisForEncounter  \
0           PBMS       2024 Aug  CRIME/VIOLATION IN PROGRESS
1           PBMS       2024 Aug  CRIME/VIOLATION IN PROGRESS
2           PBBS       2024 Aug  CRIME/VIOLATION IN PROGRESS
3           PBBN       2024 Aug  CRIME/VIOLATION IN PROGRESS
4           PBBS       2024 Aug  CRIME/VIOLATION IN PROGRESS

  Subject Injury Level Subject Injured   Age Subject Race Subject Gender  \
0            No Injury               N  17.0        BLACK           MALE
1            No Injury               N  30.0        BLACK           MALE
2            No Injury               N  19.0        OTHER           MALE
3            No Injury               N  38.0        BLACK           MALE
4      Physical Injury               Y  17.0     HISPANIC           MALE

  Force Against MOS Subject Used Force  MemberCount
0    Physical Force                  Y            2
1    Physical Force                  Y            2
2    Physical Force                  Y            2
3    Physical Force                  Y            2
4    Physical Force                  Y            2

In [37]:
single_subject_full.to_csv('TRI_SingleSubject_AnyMembers.csv', index=False)